# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast recordings 📼
docs: true
docsurl: https://radio-aktywne.github.io/gecko
email: it@radioaktywne.pl
envprefix: GECKO
events: false
imagename: services/gecko
importname: gecko
port: 31000
registry: true
releases: true
reponame: gecko
repourl: https://github.com/radio-aktywne/gecko
servicename: gecko
