# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.21.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast recordings service 📼
docs: true
docsurl: https://radio-aktywne.github.io/gecko
envprefix: GECKO
imagename: services/gecko
importname: gecko
port: 10700
registry: true
releases: true
reponame: gecko
repourl: https://github.com/radio-aktywne/gecko
servicename: gecko
