# Changes here will be overwritten by Copier; NEVER EDIT MANUALLY
_commit: 0.17.0
_src_path: gh:radio-aktywne/template-service-litestar
accountname: radio-aktywne
description: Broadcast recordings 📼
docs: true
docsurl: https://radio-aktywne.github.io/emirecords
email: it@radioaktywne.pl
envprefix: EMIRECORDS
events: false
imagename: services/emirecords
importname: emirecords
port: 31000
registry: true
releases: true
reponame: emirecords
repourl: https://github.com/radio-aktywne/emirecords
servicename: emirecords
