services:
  gecko:
    build:
      context: ./
      network: host
    environment:
      - "GECKO__SERVER__HOST=${GECKO__SERVER__HOST:-0.0.0.0}"
      - "GECKO__SERVER__PORT=${GECKO__SERVER__PORT:-31000}"
      - "GECKO__SERVER__TRUSTED=${GECKO__SERVER__TRUSTED:-*}"
      - "GECKO__BEAVER__HTTP__SCHEME=${GECKO__BEAVER__HTTP__SCHEME:-http}"
      - "GECKO__BEAVER__HTTP__HOST=${GECKO__BEAVER__HTTP__HOST:-localhost}"
      - "GECKO__BEAVER__HTTP__PORT=${GECKO__BEAVER__HTTP__PORT:-35000}"
      - "GECKO__BEAVER__HTTP__PATH=${GECKO__BEAVER__HTTP__PATH:-}"
      - "GECKO__EMERALD__S3__SECURE=${GECKO__EMERALD__S3__SECURE:-false}"
      - "GECKO__EMERALD__S3__HOST=${GECKO__EMERALD__S3__HOST:-localhost}"
      - "GECKO__EMERALD__S3__PORT=${GECKO__EMERALD__S3__PORT:-30000}"
      - "GECKO__EMERALD__S3__USER=${GECKO__EMERALD__S3__USER:-readwrite}"
      - "GECKO__EMERALD__S3__PASSWORD=${GECKO__EMERALD__S3__PASSWORD:-password}"
      - "GECKO__DEBUG=${GECKO__DEBUG:-false}"
    network_mode: host
